/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.*;
import java.text.Normalizer;
import java.util.*;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Camolo
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form manin
     */
    String[] palabras = {};
    String[] sufijos = {};
    DefaultTableModel modelo;

    public main() {
        initComponents();
        modelo = (DefaultTableModel) tbRaices.getModel();
        
    }

    public void leertxt() throws FileNotFoundException, IOException {
        BufferedReader br = new BufferedReader(new FileReader("palabras.txt"));
        BufferedReader br2 = new BufferedReader(new FileReader("sufijos.txt"));

        List<String> lineas = new ArrayList<String>();
        List<String> lineas2 = new ArrayList<String>();

        String linea = "";
        String linea2 = "";

        while ((linea = br.readLine()) != null) {
            lineas.add(linea);
        }
        while ((linea2 = br2.readLine()) != null) {
            lineas2.add(linea2);
        }

        br.close();
        br2.close();

        palabras = lineas.toArray(new String[]{});
        sufijos = lineas2.toArray(new String[]{});
    }

    public static String limpiarSignos(String texto) {
        String limpio = null;
        if (texto != null) {
            String valor = texto;
            valor = valor.toUpperCase();
            limpio = Normalizer.normalize(valor, Normalizer.Form.NFD);
            limpio = limpio.replaceAll("[^\\p{ASCII}(N\u0303)(n\u0303)(\u00A1)(\u00BF)(\u00B0)(U\u0308)(u\u0308)(\u002C)]", "");
            limpio = Normalizer.normalize(limpio, Normalizer.Form.NFC);
        }
        return limpio.toLowerCase();
    }
    public void limpiarTabla(){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tbRaices.getModel();
            int filas=tbRaices.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAnalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRaices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTexto.setColumns(20);
        txtTexto.setLineWrap(true);
        txtTexto.setRows(5);
        jScrollPane1.setViewportView(txtTexto);

        jLabel1.setText("Texto a analizar");

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultados:");

        txtResultado.setEditable(false);
        jScrollPane2.setViewportView(txtResultado);

        tbRaices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "raiz", "veces"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRaices.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbRaices);
        if (tbRaices.getColumnModel().getColumnCount() > 0) {
            tbRaices.getColumnModel().getColumn(0).setResizable(false);
            tbRaices.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnalizar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(btnAnalizar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        limpiarTabla();
        String textoOriginal = limpiarSignos(this.txtTexto.getText().trim().toLowerCase());
        textoOriginal = textoOriginal.replaceAll("[,|.|-|?|¡|!|/|;|:|¿|)|(|]", "");
        String[] text = textoOriginal.split(" ");
        try {
            leertxt();
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < text.length; i++) {
            for (int j = 0; j < palabras.length; j++) {
                if (text[i].equals(palabras[j])) {
                    text[i] = "";
                }
            }
        }
        ArrayList<String> nuevoTexto = new ArrayList<>(Arrays.asList(text));
        for (int i = (nuevoTexto.size() - 1); i >= 0; i--) {
            if ("".equals(nuevoTexto.get(i))) {
                nuevoTexto.remove(i);
            }

        }

        String resultado = "";
        ArrayList<String> raices = new ArrayList<>();
        for (int i = 0; i < nuevoTexto.size(); i++) {
            resultado += nuevoTexto.get(i) + " ";
            for (int j = 0; j < sufijos.length; j++) {
                if (nuevoTexto.get(i).endsWith(sufijos[j]) && nuevoTexto.get(i).length() > (sufijos[j].length() + 2)) {
                    nuevoTexto.set(i, nuevoTexto.get(i).replace(sufijos[j], ""));
                    raices.add(nuevoTexto.get(i));
                }
            }
        }
        Set<String> quipu = new HashSet<String>(raices);
        for (String key : quipu) {
            modelo.addRow(new Object[]{key,Collections.frequency(raices, key)});
            this.tbRaices.setModel(modelo);

        }

        this.txtResultado.setText(resultado);
        System.out.println(raices);
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbRaices;
    private javax.swing.JTextPane txtResultado;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
